[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tad-py"
version = "1.0.3"
description = "They All Die (TAD)"
readme = "README.md"
license = "GPL-3.0"
authors = [
    { name = "Florian Kolbl" },
    { name = "Jaderson Polli" },
]
requires-python = ">=3.12"

dependencies = [
    "h5py",
    "spikeinterface",
    "matplotlib",
    "numpy",
    "probeinterface",
    "scipy"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.12",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Natural Language :: English",
]

[project.urls]
homepage = "https://github.com/Neuro-Interface-Lab/TAD"
documentation = "https://tad.readthedocs.io"
repository = "https://github.com/Neuro-Interface-Lab/TAD"

[project.optional-dependencies]
dev = [
  "black",
  "build",
  "flake8",
  "furo",
  "mypy",
  "pre-commit",
  "Pygments",
  "pytest >=7.0",
  "pytest-cov",
  "sphinx",
  "sphinx_codeautolink",
  "sphinx_copybutton",
  "sphinx_gallery",
  "sphinx-mdinclude",
  "sphinx-rtd-theme",
]

[tool.setuptools.packages.find]
where = ["src"]

# ----------------------------
#   Setuptools specific part
# ----------------------------
[tool.setuptools]
include-package-data = true

[tool.bumpversion]
current_version = "1.0.3"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
allow_dirty = false
commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "Release {new_version}"
message = "Bump version: {current_version} -> {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "docs/conf.py"
search = 'release = "{current_version}"'
replace = 'release = "{new_version}"'

[[tool.bumpversion.files]]
filename = "CITATION.cff"
search = 'version: "{current_version}"'
replace = 'version: "{new_version}"'

[[tool.bumpversion.files]]
filename = ".zenodo.json"
search = '"version": "{current_version}"'
replace = '"version": "{new_version}"'

[[tool.bumpversion.files]]
filename = "src/tad/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'
